/* eslint-disable @typescript-eslint/no-unused-vars */
import Head from 'next/head'
import { ChangeEvent, useState } from 'react'
import { useForm } from 'react-hook-form'
import { MdFacebook } from 'react-icons/md'

import { optionsCarGlass, optionsYears } from '../components/Options/options'
import schema from '../components/Schema/schema'
import MyCheckbox from 'components/CheckBox'
import { Header } from 'components/Header'
import { Gmail } from 'components/Icons/Gmail'
import { Instagram } from 'components/Icons/Instagram'
import { Input } from 'components/Inputs'
import { Select } from 'components/Select'

import { yupResolver } from '@hookform/resolvers/yup'
import sendEmails from 'api/sendEmails'
import * as yup from 'yup'

import { formatPhoneNumber } from '../../utils/formatters/formatPhoneNumber'
import * as S from '../styles/PrincipalStyle/styles'

type emailData = yup.InferType<typeof schema>

export default function Home() {
  const {
    control,
    watch,
    handleSubmit,
    setValue,
    reset,
    register,
    formState: { errors }
  } = useForm({
    resolver: yupResolver(schema),
    defaultValues: {
      name: '',
      phone: '',
      emailAddress: '',
      Vin: '',
      make: '',
      model: '',
      carYear: '',
      carGlass: ''
    }
  })

  const email = watch('emailAddress')
  const VIN = watch('Vin')

  const [isChecked, setIsChecked] = useState(false)

  function handleCheckboxChange(event: ChangeEvent<HTMLInputElement>): void {
    setIsChecked(event.target.checked)
  }

  const handleForm = async (data: emailData) => {
    await sendEmails(data)
    console.log(data)
    reset();
  }

  return (
    <>
      <Head>
        <title>Autobras</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon_io/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon_io/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon_io/favicon-16x16.png"
        />
        {/* <link rel="manifest" href="/site.webmanifest" /> */}
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <S.Content>
          <S.VideoContainer>
            <S.Video autoPlay loop muted playsInline>
              <source src="autobras.mp4" type="video/mp4" />
            </S.Video>
          </S.VideoContainer>
        </S.Content>
        <S.Box>
          <S.Text>Getting your quote is really easy!</S.Text>
        </S.Box>
        <S.Container>
          <div>
            <S.Diagram src="car-glass.png" alt="diagram" />
          </div>
          <S.Form onSubmit={handleSubmit(handleForm)}>
            <S.FormContainer>
              <div className="column">
                <Input
                  type="text"
                  name="name"
                  label="Your First Name"
                  control={control}
                />
                <Input
                  type="text"
                  label="Your phone"
                  control={control}
                  {...register('phone', {
                    onChange: (e: { target: { value: string | undefined } }) => {
                      setValue('phone', formatPhoneNumber(e.target.value))
                    }
                  })}
                />
                <Input
                  type="text"
                  name="emailAddress"
                  label="Your e-mail"
                  control={control}
                />
                <Select
                  name="carYear"
                  control={control}
                  options={optionsYears}
                  label="Year"
                />
              </div>
              <div className="column">
                <Input
                  type="text"
                  name="Vin"
                  label="VIN Number*"
                  control={control}
                />
                <Input
                  type="text"
                  name="make"
                  label="Vehicle Make"
                  control={control}
                />
                <Input
                  type="text"
                  name="model"
                  label="Vehicle Model"
                  control={control}
                />
                <Select
                  name="carGlass"
                  control={control}
                  options={optionsCarGlass}
                  label="Glass"
                />
              </div>
            </S.FormContainer>
            <S.CheckBoxContainer>
              <MyCheckbox onChange={handleCheckboxChange} />
              <S.Info>
                I consent to receive SMS messages regarding my auto glass quote.
                rates my apply.
              </S.Info>
            </S.CheckBoxContainer>
            <S.Send type="submit" disabled={!isChecked}>
              Get quote
            </S.Send>
          </S.Form>
        </S.Container>
        <S.Reviews>
          <S.TextReview
            href="https://g.page/r/Cd9Ch9M9ZhyTEBI/review"
            target="_blank"
            rel="noreferrer"
          >
            Check out our reviews on Google
          </S.TextReview>

          <a
            href="https://g.page/r/Cd9Ch9M9ZhyTEBI/review"
            target="_blank"
            rel="noreferrer"
          >
            <S.Photos>
              <S.Photo src="autoGlass.jpeg" alt="autoGlass" />
              <S.Photo src="car_glass.jpeg" alt="car_glass" />
              <S.Photo src="replace.jpeg" alt="replace" />
            </S.Photos>
          </a>
          <S.Link
            href="https://g.page/r/Cd9Ch9M9ZhyTEBI/review"
            target="_blank"
            rel="noreferrer"
          >
            Click here
          </S.Link>
        </S.Reviews>
        <S.FinalContent>
          <S.BoxImg>
            <S.FootLogo src="AutoBras.png" alt="foot_Logo" />
          </S.BoxImg>
          <S.ContactUs>
            <S.Contact>
              <S.P_Contact>CONTACT US</S.P_Contact>
              <S.P_Contact>CONTÁCTENOS</S.P_Contact>
            </S.Contact>
            <S.ContentIcons>
              <S.BoxA>
                <S.SocialMedia
                  href="https://www.facebook.com/profile.php?id=100092029940465&mibextid=ZbWKwL"
                  target="_blank"
                  rel="noreferrer"
                >
                  {/* <MdFacebook size={33} color={'#1877F2'} /> */}
                  <S.FacebookIcon />

                  <p>AutoBras</p>
                </S.SocialMedia>
              </S.BoxA>
              <S.BoxA>
                <S.SocialMedia
                  href="https://instagram.com/autobras.usa?igshid=OGQ5ZDc2ODk2ZA=="
                  target="_blank"
                  rel="noreferrer"
                >
                  <Instagram />
                  <p>@Autobras.usa</p>
                </S.SocialMedia>
              </S.BoxA>
              <S.BoxA>
                <S.SocialMedia
                  href="mailto:Autobrasglass@gmail.com?subject=Quote&body=Hi%20I%20get%20a%20quote%20please"
                  target="_blank"
                  rel="noreferrer"
                >
                  <Gmail />

                  <p>autobrasglass@gmail.com</p>
                </S.SocialMedia>
              </S.BoxA>
            </S.ContentIcons>
          </S.ContactUs>
        </S.FinalContent>
      </main>
    </>
  )
}
